//go:build integration

// Integration tests run against real PostgreSQL and Oracle databases.
// They are gated behind the `integration` build tag and read DSNs from
// the POSTGRES_DSN / ORACLE_DSN environment variables. The Makefile's
// `integration` target boots docker-compose, exports the DSNs, runs
// `go test -tags=integration ./...`, and tears the stack down.
//
// A dialect's test cases are skipped (not failed) when its DSN is unset,
// so a developer can iterate on PostgreSQL alone without booting Oracle.
//
// Tables are prefixed `raizel_test_` so they don't collide with whatever
// schema may already live in a shared dev database.

package raizel_test

import (
	"context"
	"os"
	"testing"
	"time"

	"github.com/rjansen/raizel"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "github.com/sijms/go-ora/v2"
)

// dialectCase describes one engine the integration suite exercises.
type dialectCase struct {
	name      string
	driver    string
	dsnEnvVar string
	dialect   raizel.Dialect
	createSQL string
}

const integTable = "raizel_test_bills"

var dialectCases = []dialectCase{
	{
		name:      "postgres",
		driver:    "pgx",
		dsnEnvVar: "POSTGRES_DSN",
		dialect:   raizel.DialectPostgres,
		createSQL: `CREATE TABLE ` + integTable + ` (
			id BIGSERIAL PRIMARY KEY,
			title TEXT NOT NULL,
			amount DOUBLE PRECISION NOT NULL,
			paid_at TIMESTAMPTZ
		)`,
	},
	{
		name:      "oracle",
		driver:    "oracle",
		dsnEnvVar: "ORACLE_DSN",
		dialect:   raizel.DialectOracle,
		createSQL: `CREATE TABLE ` + integTable + ` (
			id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR2(255) NOT NULL,
			amount BINARY_DOUBLE NOT NULL,
			paid_at TIMESTAMP WITH TIME ZONE
		)`,
	},
}

func openDialect(t *testing.T, c dialectCase) *raizel.DB {
	t.Helper()
	dsn := os.Getenv(c.dsnEnvVar)
	if dsn == "" {
		t.Skipf("%s not set — skipping %s integration tests", c.dsnEnvVar, c.name)
	}
	rz, err := raizel.Open(c.dialect, dsn)
	if err != nil {
		t.Fatalf("open %s: %v", c.name, err)
	}
	if err := rz.PingContext(context.Background()); err != nil {
		t.Fatalf("ping %s: %v", c.name, err)
	}
	t.Cleanup(func() { _ = rz.Close() })

	// Pre-drop any leftover from a previous run, then create fresh.
	_, _ = rz.SQL().Exec("DROP TABLE " + integTable)
	if _, err := rz.SQL().Exec(c.createSQL); err != nil {
		t.Fatalf("create table on %s: %v", c.name, err)
	}
	t.Cleanup(func() { _, _ = rz.SQL().Exec("DROP TABLE " + integTable) })
	return rz
}

type integBill struct {
	ID     int64      `db:"id"`
	Title  string     `db:"title"`
	Amount float64    `db:"amount"`
	PaidAt *time.Time `db:"paid_at"`
}

// TestIntegration_CRUD verifies that the same Query / QueryOne / Exec /
// ExecNamed code paths used by the unit tests also round-trip cleanly
// against real PostgreSQL and Oracle.
func TestIntegration_CRUD(t *testing.T) {
	for _, c := range dialectCases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			db := openDialect(t, c)
			ctx := context.Background()

			when := time.Date(2026, 4, 1, 12, 0, 0, 0, time.UTC)
			b1 := integBill{Title: "rent", Amount: 1500, PaidAt: &when}
			b2 := integBill{Title: "power", Amount: 80, PaidAt: nil}
			if _, err := raizel.ExecNamed(ctx, db,
				`INSERT INTO `+integTable+` (title, amount, paid_at) VALUES (:title, :amount, :paid_at)`,
				b1, b2); err != nil {
				t.Fatalf("ExecNamed batch: %v", err)
			}

			rows, err := raizel.Query[integBill](ctx, db,
				"SELECT id, title, amount, paid_at FROM "+integTable+" ORDER BY id")
			if err != nil {
				t.Fatalf("Query: %v", err)
			}
			if len(rows) != 2 {
				t.Fatalf("got %d rows, want 2", len(rows))
			}
			if rows[0].Title != "rent" || rows[0].PaidAt == nil {
				t.Errorf("rent row: %+v", rows[0])
			}
			if rows[1].Title != "power" || rows[1].PaidAt != nil {
				t.Errorf("power row: %+v", rows[1])
			}

			_, err = raizel.QueryOne[integBill](ctx, db,
				"SELECT id, title, amount, paid_at FROM "+integTable+" WHERE title = "+
					c.dialect.Placeholder(1), "missing")
			if err == nil {
				t.Errorf("expected ErrNotFound")
			}

			sum, err := raizel.QueryOne[float64](ctx, db,
				"SELECT SUM(amount) FROM "+integTable)
			if err != nil {
				t.Fatalf("sum: %v", err)
			}
			if sum != 1580 {
				t.Errorf("sum: got %v, want 1580", sum)
			}
		})
	}
}

// TestIntegration_BatchRollback proves the auto-tx rollback works against
// real engines: a batch where the second model violates a constraint
// must leave the first row uncommitted.
func TestIntegration_BatchRollback(t *testing.T) {
	for _, c := range dialectCases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			db := openDialect(t, c)
			ctx := context.Background()

			rows := []integBill{
				{Title: "first", Amount: 10},
				{Title: "second", Amount: 20},
			}
			// Force a NOT NULL violation on amount by omitting it from the
			// INSERT column list — the table requires it.
			_, err := raizel.ExecNamed(ctx, db,
				`INSERT INTO `+integTable+` (title) VALUES (:title)`, rows[0], rows[1])
			if err == nil {
				t.Fatal("expected NOT NULL violation")
			}
			n, err := raizel.QueryOne[int64](ctx, db, "SELECT COUNT(*) FROM "+integTable)
			if err != nil {
				t.Fatal(err)
			}
			if n != 0 {
				t.Errorf("rollback failed: count=%d", n)
			}
		})
	}
}

const integArrayTable = "raizel_test_docs"

type integDoc struct {
	ID     int64    `db:"id"`
	Labels []string `db:"labels"`
}

// TestIntegration_ArrayRoundTrip proves []string fields round-trip through
// PostgreSQL's native TEXT[] and Oracle's JSON CLOB without any
// dialect-specific code in the caller.
func TestIntegration_ArrayRoundTrip(t *testing.T) {
	for _, c := range dialectCases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			db := openDialect(t, c)
			ctx := context.Background()

			var ddl string
			switch c.dialect {
			case raizel.DialectPostgres:
				ddl = `CREATE TABLE ` + integArrayTable + ` (
					id BIGINT PRIMARY KEY,
					labels TEXT[] NOT NULL DEFAULT '{}'
				)`
			case raizel.DialectOracle:
				ddl = `CREATE TABLE ` + integArrayTable + ` (
					id NUMBER(19) PRIMARY KEY,
					labels CLOB DEFAULT '[]' NOT NULL CHECK (labels IS JSON)
				)`
			}
			_, _ = db.SQL().Exec("DROP TABLE " + integArrayTable)
			if _, err := db.SQL().Exec(ddl); err != nil {
				t.Fatalf("create array table on %s: %v", c.name, err)
			}
			t.Cleanup(func() { _, _ = db.SQL().Exec("DROP TABLE " + integArrayTable) })

			if _, err := raizel.ExecNamed(ctx, db,
				"INSERT INTO "+integArrayTable+" (id, labels) VALUES (:id, :labels)",
				integDoc{ID: 1, Labels: []string{"INBOX", "IMPORTANT"}},
				integDoc{ID: 2, Labels: nil}); err != nil {
				t.Fatalf("ExecNamed: %v", err)
			}

			got, err := raizel.QueryOne[integDoc](ctx, db,
				"SELECT id, labels FROM "+integArrayTable+" WHERE id = "+c.dialect.Placeholder(1), 1)
			if err != nil {
				t.Fatalf("QueryOne: %v", err)
			}
			if len(got.Labels) != 2 || got.Labels[0] != "INBOX" || got.Labels[1] != "IMPORTANT" {
				t.Errorf("labels round-trip on %s: got %#v", c.name, got.Labels)
			}

			empty, err := raizel.QueryOne[integDoc](ctx, db,
				"SELECT id, labels FROM "+integArrayTable+" WHERE id = "+c.dialect.Placeholder(1), 2)
			if err != nil {
				t.Fatalf("QueryOne empty: %v", err)
			}
			if len(empty.Labels) != 0 {
				t.Errorf("empty labels round-trip on %s: got %#v", c.name, empty.Labels)
			}
		})
	}
}
