.PHONY: postgres_run
postgres_run:
	@echo "$(REPO) postgres_run"
	@docker run --rm -d --name postgres-run --net=host \
		-v "$(shell pwd)/etc/test/integration/postgres/scripts:/docker-entrypoint-initdb.d" postgres:11.1
	@sleep 5 #wait until database is ready

.PHONY: postgres_kill
postgres_kill:
	@echo "$(REPO) postgres_kill"
	@docker kill postgres-run
